language: bash
services: docker
before_install:
  - cd RestWithSpringBootUdemy/
  - echo "We are in the Docker folder!"
script:
  - docker-compose build
before_deploy:
  - echo "UserName...."
  - echo "${DOCKER_USERNAME}"
  - echo "${DOCKER_PASSWORD}"
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider: script
  script:
    - docker push achrafh01/mysql-rest-with-spring-boot-udemy || echo "Failed to push MySQL image";
    - docker push achrafh01/rest-with-spring-boot-udemy || echo "Failed to push REST image";
  on:
    all_branches: true
notifications:
  email: false
