language: bash
services: docker
before_install:
  - cd RestWithSpringBootUdemy/
  - echo "We are in the Docker folder!"
script:
  - docker-compose build
deploy:
  provider: script
  script:
  - echo "test...."
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push achrafh01/mysql-rest-with-spring-boot-udemy;
  - docker push achrafh01/rest-with-spring-boot-udemy;
  on:
    all_branches: true
notifications:
  email: false
