language: bash
services: docker
before_install:
  - cd RestWithSpringBootUdemy/
  - echo "We are in the Docker folder!"
script:
  - docker-compose build
deploy:
  provider: script
  script:
    bash docker_push
  on:
    all_branches: true
notifications:
  email: false
